name: Testing

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  pytest:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Setup venv for testing
        run: uv venv

      - name: Install dependencies
        run: uv sync --extra test
        # run: uv pip install -r pyproject.toml --extra test

      - name: Test with pytest
        run: uv run pytest
