name: Testing

on:
  # push:
  #   tags:
  #     - "v*.*.*"
  workflow_call:
  workflow_dispatch:

jobs:
  pytest:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Setup venv for testing
        run: uv venv

      - name: Install dependencies
        run: uv sync --extra test

      - name: Cache databases
        id: cache-databases
        uses: actions/cache@v4
        with:
          path: ~/.cache/refidxdb
          key: ${{ runner.os }}-databases-${{ hashFiles('pyproject.toml') }}

      - name: Download databases
        if: steps.cache-databases.outputs.cache-hit != 'true'
        run: uv run refidxdb db --download all

      - name: Test and coverage report with pytest
        run: uv run pytest --cov=./ --cov-report xml

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
